blank_issues_enabled: false # ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã‚’ä½¿ã‚ãªã„ã€Œç©ºç™½ã®Issueã€ä½œæˆã‚’ç¦æ­¢ã™ã‚‹
contact_links:
    - name: ğŸ’¬ è³ªå•ãƒ»ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
      url: https://github.com/andolab/andolab-shop/discussions
      about: ãƒã‚°ã‚„æ©Ÿèƒ½è¿½åŠ ã§ã¯ãªãã€å˜ãªã‚‹è³ªå•ã‚„ã‚¢ã‚¤ãƒ‡ã‚¢ã®ç›¸è«‡ã¯ã“ã¡ã‚‰ã¸ã©ã†ãã€‚
